spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  liquibase:
    change-log: classpath:db/changelog/db-changelog.xml

  logging:
    level:
      com.ed.sysbankcards: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html